#!/usr/bin/env bash

if [ "$1" == "start" ]; then
    docker-compose start
fi

if [ "$1" == "stop" ]; then
    docker-compose stop
fi

if [ "$1" == "update" ]; then    
    docker-compose pull && docker-compose down && docker-compose up -d
fi

if [ "$1" == "setup" ]; then
  echo 'Setting system...' \
  && rm -rf rhymix; git clone -b stage https://github.com/woosungchoi/docker-rhymix rhymix \
  && cd rhymix \
  && sed -i "s/<domain>/$2/g" docker-compose.yml \
  && sed -i "s/<domain>/$2/g" docker-compose.production.yml \
  && sed -i "s/<email>/$3/g" docker-compose.yml \
  && sed -i "s/<domain>/$2/g" nginx/conf.d/rhymix.conf \
  && sed -i "s/<domain>/$2/g" nginx/conf.d/portainer.conf \
  && sed -i "s/<domain>/$2/g" nginx/conf.d/phpmyadmin.conf \
  && echo 'Setting timezone to Asia/Seoul...' \
  && sudo timedatectl set-timezone Asia/Seoul \
  && echo 'Installing Docker...' \
  && sudo apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y \
  && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - \
  && sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" -y \
  && sudo apt update -y \
  && sudo apt install docker-ce docker-ce-cli containerd.io -y \
  && echo 'Installing Docker Compose...' \
  && sudo curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose \
  && sudo chmod +x /usr/local/bin/docker-compose \
  && echo 'Installing SSL...' \
  && sudo docker-compose up \
  && echo 'Preparing docker-compose up' \
  && sudo docker-compose down -v \
  && sudo mkdir -p /usr/share/nginx/html;
  curl -sSLo nginx/conf.d/options-ssl-nginx https://raw.githubusercontent.com/certbot/certbot/master/certbot-nginx/certbot_nginx/_internal/tls_configs/options-ssl-nginx.conf \
  && curl -sSLo nginx/conf.d/rhymix-rewrite https://raw.githubusercontent.com/rhymix/rhymix/master/common/manual/server_config/rhymix-nginx.conf \
  && sudo chmod a+x build/docker-entrypoint.sh \
  && mv docker-compose.yml docker-compose.ssl.yml \
  && mv docker-compose.production.yml docker-compose.yml \
  && echo 'Configuring cron...' \
  && echo "0 23 * * * docker start certbot && docker restart nginx >> /var/log/docker_cron.log 2>&1" >> mycron \
  && sudo crontab mycron; rm mycron \
  && echo 'Starting Docker ...' \
  && sudo docker-compose up -d  \
  && echo 'Done! 🎉' \
  && echo 'by Rafael Correa Gomes and Woosung Choi' \
  && echo 'Access your host: https://'$2;
fi
