version: '3'
services:

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    ports:
      - 80:80
    volumes:
      - ./ssl/:/etc/letsencrypt/
    command: certonly --staging --standalone -d <domain> -d www.<domain> -d port.<domain> -d pma.<domain> -m <email> --no-eff-email --agree-tos
